version: '3.8'

services:
    main:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/app
        - .env.docker:/app/.env
      ports:
        - 8000:8000
      depends_on:
        - db
    db:
      platform: linux/x86_64
      image: mysql:8.0
      command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      environment:
        MYSQL_DATABASE: roomvu
        MYSQL_USER: roomvu
        MYSQL_ROOT: root
        MYSQL_PASSWORD: roomvu
      volumes:
        - ./storage/mysql:/var/lib/mysql
      ports:
        - 3306:3306
